version: "3.8"

services:

  auth-mgmt:
    image: devplazaadmin/auth-mgmt:latest
    container_name: auth-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?schema=auth_mgmt_db
    ports:
      - "3000:3000"
    networks:
      - devplaza-network

  product-mgmt:
    image: devplazaadmin/product-mgmt:latest
    container_name: product-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?schema=product_mgmt_db
    ports:
      - "3004:3004"
    networks:
      - devplaza-network

  tenant-mgmt:
    image: devplazaadmin/tenant-mgmt:latest
    container_name: tenant-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?schema=tenant_mgmt_db
    ports:
      - "3001:3001"
    networks:
      - devplaza-network

  user-mgmt:
    image: devplazaadmin/user-mgmt:latest
    container_name: user-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME?schema=user_mgmt_db
    ports:
      - "3002:3002"
    networks:
      - devplaza-network

  frontend:
    image: devplazaadmin/devplazafrontend:latest
    container_name: devplaza-customer
    ports:
      - "5173:5173"
    depends_on:
      - auth-mgmt
      - user-mgmt
      - tenant-mgmt
      - product-mgmt
    networks:
      - devplaza-network

networks:
  devplaza-network:
    driver: bridge