version: "3.8"

services:

  auth-mgmt:
    image: Sarathroy1502/auth-mgmt:latest
    # build: ../DevPlazaBackEnd/auth-mgmt
    container_name: auth-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/postgres?schema=auth_mgmt_db
    ports:
      - "3000:3000"
    networks:
      - devplaza-network

  product-mgmt:
    image: Sarathroy1502/product-mgmt:latest
    # build: ../DevPlazaBackEnd/product-mgmt
    container_name: product-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/postgres?schema=product_mgmt_db
    ports:
      - "3004:3004"
    networks:
      - devplaza-network

  tenant-mgmt:
    image: Sarathroy1502/tenant-mgmt:latest
    # build: ../DevPlazaBackEnd/tenant-mgmt
    container_name: tenant-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/postgres?schema=tenant_mgmt_db
    ports:
      - "3001:3001"
    networks:
      - devplaza-network

  user-mgmt:
    image: Sarathroy1502/user-mgmt:latest
    # build: ../DevPlazaBackEnd/user-mgmt
    container_name: user-mgmt
    environment:
      - DATABASE_URL=postgresql://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/postgres?schema=user_mgmt_db
    ports:
      - "3002:3002"
    networks:
      - devplaza-network

  frontend:
    image: Sarathroy1502/devplaza-customer:latest
    # build: ../DevPlazaFrontEnd/DevPlazaCustomer
    container_name: devplaza-customer
    ports:
      - "5173:5173"
    depends_on:
      - auth-mgmt
      - user-mgmt
      - tenant-mgmt
      - product-mgmt
    networks:
      - devplaza-network

networks:
  devplaza-network:
    driver: bridge